/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bibliotecademusicaeletronica;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author paulo
 */
public class Menu extends javax.swing.JFrame {

    public String genero;
    public String prog;
    public String psyprog;
    public String groove;
    public String morning;
    public String goa;
    public String night;
    public String twi;
    public String forest;
    public String hi;
    public String dark;

    public String pesquisar;
    
    List<String> lista = new ArrayList();

    Arquivo aq = new Arquivo();
    Musica ms = new Musica();

    DefaultListModel dlm = new DefaultListModel();

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelNome = new javax.swing.JLabel();
        TextNome = new javax.swing.JTextField();
        labelGenero = new javax.swing.JLabel();
        labelDiurno = new javax.swing.JLabel();
        labelNoturno = new javax.swing.JLabel();
        ProgBox = new javax.swing.JCheckBox();
        GrooveBox = new javax.swing.JCheckBox();
        MorningBox = new javax.swing.JCheckBox();
        GoaBox = new javax.swing.JCheckBox();
        ForestBox = new javax.swing.JCheckBox();
        NightBox = new javax.swing.JCheckBox();
        DarkBox = new javax.swing.JCheckBox();
        HiBox = new javax.swing.JCheckBox();
        TwilightBox = new javax.swing.JCheckBox();
        PsyProgBox = new javax.swing.JCheckBox();
        botaoSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaCadastros = new javax.swing.JList<>();
        labelBuscar = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        botaoBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        busca2text = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        botaoEncontrar = new javax.swing.JButton();
        labelDeletar = new javax.swing.JLabel();
        novoNometext = new javax.swing.JTextField();
        botaoDeletar = new javax.swing.JButton();
        novotext = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelNome.setText("Nome:");

        TextNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNomeActionPerformed(evt);
            }
        });

        labelGenero.setText("Gênero:");

        labelDiurno.setText("Diurno:");

        labelNoturno.setText("Noturno:");

        ProgBox.setText("Prog Comercial");
        ProgBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProgBoxActionPerformed(evt);
            }
        });

        GrooveBox.setText("Full On Groove");
        GrooveBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrooveBoxActionPerformed(evt);
            }
        });

        MorningBox.setText("Full On Morning");
        MorningBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MorningBoxActionPerformed(evt);
            }
        });

        GoaBox.setText("Goa");
        GoaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoaBoxActionPerformed(evt);
            }
        });

        ForestBox.setText("Forest");
        ForestBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForestBoxActionPerformed(evt);
            }
        });

        NightBox.setText("Full On Night");
        NightBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NightBoxActionPerformed(evt);
            }
        });

        DarkBox.setText("Dark");
        DarkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DarkBoxActionPerformed(evt);
            }
        });

        HiBox.setText("Hi-Tech");
        HiBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HiBoxActionPerformed(evt);
            }
        });

        TwilightBox.setText("Twilight ");
        TwilightBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwilightBoxActionPerformed(evt);
            }
        });

        PsyProgBox.setText("Psy Progressive");
        PsyProgBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PsyProgBoxActionPerformed(evt);
            }
        });

        botaoSalvar.setText("SALVAR");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listaCadastros);

        labelBuscar.setText("Pesquisar por gênero:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "Prog Comercial", "Psy Progressive", "Full On Groove", "Full On Morning ", "Goa", "Full On Night", "Twilight", "Forest", "Hi-Tech", "Dark" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        botaoBuscar.setText("BUSCAR");
        botaoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("Editar: ");

        busca2text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busca2textActionPerformed(evt);
            }
        });

        jLabel2.setText("Busque o nome da track/Álbum:");

        botaoEncontrar.setText("ALTERAR");
        botaoEncontrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEncontrarActionPerformed(evt);
            }
        });

        labelDeletar.setText("Deletar Track:");

        novoNometext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoNometextActionPerformed(evt);
            }
        });

        botaoDeletar.setText("DELETAR");
        botaoDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDeletarActionPerformed(evt);
            }
        });

        novotext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novotextActionPerformed(evt);
            }
        });

        jLabel3.setText("Novo nome:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(GrooveBox)
                                            .addComponent(GoaBox)
                                            .addComponent(MorningBox)
                                            .addComponent(PsyProgBox)
                                            .addComponent(ProgBox))
                                        .addGap(30, 30, 30))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(labelDiurno)
                                        .addGap(107, 107, 107)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NightBox)
                                    .addComponent(DarkBox)
                                    .addComponent(HiBox)
                                    .addComponent(ForestBox)
                                    .addComponent(TwilightBox)
                                    .addComponent(labelNoturno)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoSalvar))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botaoBuscar)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(botaoEncontrar)
                                .addComponent(labelDeletar)
                                .addComponent(botaoDeletar)
                                .addComponent(novoNometext, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                .addComponent(busca2text)
                                .addComponent(novotext))
                            .addComponent(jLabel3))
                        .addGap(0, 24, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelGenero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextNome, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(labelBuscar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNome)
                            .addComponent(TextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelBuscar))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelGenero)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDiurno)
                            .addComponent(labelNoturno)
                            .addComponent(botaoBuscar))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NightBox)
                            .addComponent(ProgBox, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TwilightBox)
                        .addComponent(jLabel2))
                    .addComponent(PsyProgBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ForestBox)
                        .addComponent(GrooveBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(busca2text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HiBox)
                            .addComponent(MorningBox, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DarkBox)
                            .addComponent(GoaBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(35, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(novotext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoEncontrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelDeletar)
                        .addGap(18, 18, 18)
                        .addComponent(novoNometext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoDeletar)
                        .addGap(56, 56, 56))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNomeActionPerformed

    private void ProgBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProgBoxActionPerformed

    }//GEN-LAST:event_ProgBoxActionPerformed

    private void MorningBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MorningBoxActionPerformed

    }//GEN-LAST:event_MorningBoxActionPerformed

    private void GoaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoaBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GoaBoxActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        ms.nome = TextNome.getText();
        TextNome.setText("");

        if (ProgBox.isSelected()) {
            lista.add("Prog Comercial");
            ProgBox.setSelected(false);
        }
        if (PsyProgBox.isSelected()) {
            lista.add("Psy Progressive");
            PsyProgBox.setSelected(false);
        }
        if (GrooveBox.isSelected()) {
            lista.add("Full On Groove");
            GrooveBox.setSelected(false);
        }
        if (MorningBox.isSelected()) {
            lista.add("Full On Morning");
            MorningBox.setSelected(false);
        }
        if (GoaBox.isSelected()) {
            lista.add("Goa");
            GoaBox.setSelected(false);
        }
        if (NightBox.isSelected()) {
            lista.add("Full On Night");
            NightBox.setSelected(false);
        }
        if (TwilightBox.isSelected()) {
            lista.add("Twilight");
            TwilightBox.setSelected(false);
        }
        if (ForestBox.isSelected()) {
            lista.add("Forest");
            ForestBox.setSelected(false);
        }
        if (DarkBox.isSelected()) {
            lista.add("Dark");
            DarkBox.setSelected(false);
        }
        if (HiBox.isSelected()) {
            lista.add("Hi-Tech");
            HiBox.setSelected(false);
        }
        
        try {
            aq.salvarArquivo(ms.nome,lista);
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String novoCadastro = ms.nome;
        
        listaCadastros.setModel(dlm);
        dlm.addElement(novoCadastro);
        
        JOptionPane.showMessageDialog(null, "Adicionado com sucesso!");
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void PsyProgBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PsyProgBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PsyProgBoxActionPerformed

    private void GrooveBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrooveBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GrooveBoxActionPerformed

    private void NightBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NightBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NightBoxActionPerformed

    private void TwilightBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwilightBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TwilightBoxActionPerformed

    private void ForestBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForestBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ForestBoxActionPerformed

    private void HiBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HiBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HiBoxActionPerformed

    private void DarkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DarkBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DarkBoxActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void botaoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarActionPerformed
        
        pesquisar = (String) jComboBox1.getSelectedItem();
        try {
            aq.buscarArquivo(pesquisar);
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_botaoBuscarActionPerformed

    private void botaoEncontrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEncontrarActionPerformed
        ms.nomeErrado = busca2text.getText();
        ms.nomeNovo = novotext.getText();
        try {
            aq.encontrarArquivo(ms.nomeErrado, ms.nomeNovo);
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        busca2text.setText("");
        novotext.setText("");
        JOptionPane.showMessageDialog(null, "Alterado com sucesso!");
    }//GEN-LAST:event_botaoEncontrarActionPerformed

    private void busca2textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busca2textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_busca2textActionPerformed

    private void botaoDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDeletarActionPerformed
        ms.nomeDel = novoNometext.getText();
        
        aq.deletarArquivo(ms.nomeDel);
        
        novoNometext.setText("");
        JOptionPane.showMessageDialog(null, "Deletado com sucesso!");
    }//GEN-LAST:event_botaoDeletarActionPerformed

    private void novoNometextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoNometextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novoNometextActionPerformed

    private void novotextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novotextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novotextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox DarkBox;
    private javax.swing.JCheckBox ForestBox;
    private javax.swing.JCheckBox GoaBox;
    private javax.swing.JCheckBox GrooveBox;
    private javax.swing.JCheckBox HiBox;
    private javax.swing.JCheckBox MorningBox;
    private javax.swing.JCheckBox NightBox;
    private javax.swing.JCheckBox ProgBox;
    private javax.swing.JCheckBox PsyProgBox;
    private javax.swing.JTextField TextNome;
    private javax.swing.JCheckBox TwilightBox;
    private javax.swing.JButton botaoBuscar;
    private javax.swing.JButton botaoDeletar;
    private javax.swing.JButton botaoEncontrar;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JTextField busca2text;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBuscar;
    private javax.swing.JLabel labelDeletar;
    private javax.swing.JLabel labelDiurno;
    private javax.swing.JLabel labelGenero;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNoturno;
    private javax.swing.JList<String> listaCadastros;
    private javax.swing.JTextField novoNometext;
    private javax.swing.JTextField novotext;
    // End of variables declaration//GEN-END:variables
}
